spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: ${PORT:8080}
gemini:
  api:
    key: ${GEMINI_API_KEY}
app:
  resend:
    api-key: ${RESEND_API_KEY}
    from-email: "GridMind <soporte@gridmind.lat>"
ia:
  service:
    url: ${IA_SERVICE_URL:https://ia.gridmind.lat/predict}
